# .github/workflows/export-sarif.yml
name: Export code-scanning SARIF to repo

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"   # Mondays 03:00 UTC

permissions:
  contents: write
  security-events: read

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Get the most recent analysis id (optionally filter by tool_name, ref, etc.)
      - name: Get latest analysis id
        id: list
        run: |
          ANALYSIS_ID=$(curl -sSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/code-scanning/analyses?per_page=1" \
            | jq -r '.[0].id')
          echo "analysis_id=$ANALYSIS_ID" >> "$GITHUB_OUTPUT"

      # Download that analysis as SARIF
      - name: Download SARIF
        run: |
          mkdir -p security/reports
          curl -sSL \
            -H "Accept: application/sarif+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/code-scanning/analyses/${{ steps.list.outputs.analysis_id }}" \
            -o security/reports/code-scanning-${{ github.run_id }}.sarif.json

      # Commit SARIF back to the same repo
      - name: Commit SARIF file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: export latest code-scanning SARIF"
          file_pattern: security/reports/*.sarif.json
