name: Export code-scanning SARIF to repo

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"  # Mondays 03:00 UTC

permissions:
  contents: write
  security-events: read

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Optional: append ?tool_name=CodeQL&ref=refs/heads/main
      - name: Get latest analysis id
        id: list
        run: |
          set -euo pipefail
          API="https://api.github.com/repos/${{ github.repository }}/code-scanning/analyses?per_page=1"
          ANALYSIS_ID=$(curl -sSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "$API" | jq -r '.[0].id')
          if [ -z "${ANALYSIS_ID}" ] || [ "${ANALYSIS_ID}" = "null" ]; then
            echo "No code-scanning analyses found. Has a scan run yet?"
            exit 1
          fi
          echo "analysis_id=$ANALYSIS_ID" >> "$GITHUB_OUTPUT"

      - name: Download SARIF
        run: |
          set -euo pipefail
          mkdir -p security/reports
          curl -sSL \
            -H "Accept: application/sarif+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/code-scanning/analyses/${{ steps.list.outputs.analysis_id }}" \
            -o security/reports/code-scanning-${{ github.run_id }}.sarif.json

      - name: Normalize SARIF for strict viewers
        run: |
          set -euo pipefail
          in=security/reports/code-scanning-${{ github.run_id }}.sarif.json
          out=security/reports/code-scanning-${{ github.run_id }}.sarif.cleaned.json

          jq '
            def walk(f):
              . as $in
              | if type == "object" then
                  reduce keys[] as $k ({}; . + { ($k): ($in[$k] | walk(f)) }) | f
                elif type == "array" then
                  map(walk(f)) | f
                else f end;

            def is_minimal_rule:
              (type=="object") and has("id") and ((keys|length)==1);

            .runs |= map(
              # A) Remove minimal artifacts array
              del(.artifacts)

              # B) Strip artifactLocation.index pointers
              | walk(
                  if type=="object" and has("artifactLocation") and (.artifactLocation|type)=="object"
                  then .artifactLocation |= del(.index) else . end
                )

              # C) Remove empty message objects
              | walk(
                  if type=="object" and has("message") and (.message|type)=="object"
                     and ((.message|keys|length)==0)
                  then del(.message) else . end
                )

              # D) SARIF1001: drop rule.name when it equals rule.id
              | (if (.tool.driver.rules? // null) != null then
                   .tool.driver.rules |= map( if (.name? and .id? and .name == .id) then del(.name) else . end )
                 else . end)
              | (if (.tool.extensions? // null) != null then
                   .tool.extensions |= map(
                     if (.rules? // null) != null
                     then .rules |= map( if (.name? and .id? and .name == .id) then del(.name) else . end )
                     else . end
                   )
                 else . end)

              # E) Drop rules arrays if every rule is minimal
              | (if (.tool.driver.rules? // null) != null and
                     ( .tool.driver.rules | length > 0 ) and
                     ( all(.tool.driver.rules[]; is_minimal_rule) )
                 then del(.tool.driver.rules) else . end)
              | (if (.tool.extensions? // null) != null then
                   .tool.extensions |= map(
                     if (.rules? // null) != null and
                        ( .rules | length > 0 ) and
                        ( all(.rules[]; is_minimal_rule) )
                     then del(.rules) else . end
                   )
                 else . end)

              # F) Results normalization (+ 2007 uriBaseIds)
              | (if (.results? // null) != null then
                   .results |= map(
                     if (.rule? // null) != null and (.rule|type)=="object" then
                       # If rule minimal -> prefer ruleId and drop rule; else keep rule, drop ruleId/ruleIndex
                       ( if ((.rule|type)=="object" and (.rule|keys|length)==1 and (.rule|has("id"))) then
                           ( .ruleId = (.ruleId // .rule.id) ) | del(.rule)
                         else
                           del(.ruleId, .ruleIndex
