# .github/workflows/export-sarif.yml
name: Export code-scanning SARIF to repo

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"

permissions:
  contents: write
  security-events: read

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get latest analysis id (default branch)
        id: list
        run: |
          ANALYSIS_ID=$(curl -sSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/code-scanning/analyses?per_page=1" \
            | jq -r '.[0].id')
          echo "analysis_id=$ANALYSIS_ID" >> "$GITHUB_OUTPUT"

      - name: Download SARIF
        run: |
          mkdir -p security/reports
          curl -sSL \
            -H "Accept: application/sarif+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/code-scanning/analyses/${{ steps.list.outputs.analysis_id }}" \
            -o security/reports/code-scanning-${{ github.run_id }}.sarif.json

      # Fix 1: normalize away arrays that trip SARIF2004
     # - name: Normalize SARIF (drop minimal arrays)
      #  run: |
       #   in=security/reports/code-scanning-${{ github.run_id }}.sarif.json
       #   out=security/reports/code-scanning-${{ github.run_id }}.sarif.cleaned.json
       #   jq '
        #    .runs |= map(
        #      if (.tool.driver.rules? // null) != null and
         #        ( (.tool.driver.rules | length) > 0 ) and
         #        ( all(.tool.driver.rules[]; (keys | length) == 1 and has("id")) )
         #     then del(.tool.driver.rules) else . end
         #   )
        #  ' "$in" > "$out"
        #  mv "$out" "$in"

      # Fix 2: validate with Microsoft SARIF Multitool
      - name: Validate SARIF
        uses: microsoft/sarif-actions@v0.1
        with:
          command: "validate security/reports/code-scanning-${{ github.run_id }}.sarif.json"
      
      - name: Reformat SARIF
        uses: microsoft/sarif-actions@v0.1
        with:
          command: "reformat security/reports/code-scanning-${{ github.run_id }}.sarif.json"


      - name: Commit SARIF file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: export latest code-scanning SARIF (normalized)"
          file_pattern: security/reports/*.sarif.json
